Repository laravel-hyperf/components, pull requests merged in 2025-03, with the labels that each got.

#43 feat: support setting shouldListenCallback in telescope
  src/telescope/src/ListensForStorageOpportunities.php
Labels: feature

#45 feat: add make:mail and make:notification for devtool
  src/devtool/src/ConfigProvider.php
  src/devtool/src/Generator/BatchesTableCommand.php
  src/devtool/src/Generator/MailCommand.php
  src/devtool/src/Generator/NotificationCommand.php
  src/devtool/src/Generator/NotificationTableCommand.php
  src/devtool/src/Generator/QueueFailedTableCommand.php
  src/devtool/src/Generator/QueueTableCommand.php
  src/devtool/src/Generator/SessionTableCommand.php
  src/devtool/src/Generator/stubs/mail.stub
  src/devtool/src/Generator/stubs/markdown-mail.stub
  src/devtool/src/Generator/stubs/markdown-notification.stub
  src/devtool/src/Generator/stubs/markdown.stub
  src/devtool/src/Generator/stubs/notification.stub
  src/devtool/src/Generator/stubs/view-mail.stub
  src/http/src/CoreMiddleware.php
  src/notifications/src/Messages/MailMessage.php
  src/support/src/Contracts/Renderable.php
Labels: feature

#47 refactor: implement RouteDependency to and improve performance for getting route params
  src/foundation/composer.json
  src/foundation/src/Providers/FormRequestServiceProvider.php
  src/http/src/CoreMiddleware.php
  src/http/src/RouteDependency.php
  tests/Http/RouteDependencyTest.php
Labels: enhancement

#48 lcobucci driver should get from config
  src/jwt/src/JWTManager.php
Labels: bug

#49 fix: fix tag option in vendor:publish command
  src/foundation/src/Console/Commands/VendorPublishCommand.php
Labels: bug

#50 feat: support streamed content in testing
  src/foundation/src/Testing/Http/ServerResponse.php
  src/foundation/src/Testing/Http/TestClient.php
  src/foundation/src/Testing/Http/TestResponse.php
  tests/Foundation/Testing/Concerns/MakesHttpRequestsTest.php
  tests/Foundation/fixtures/hyperf/routes/test-api.php
Labels: feature

#51 feat: add extended validation rule class
  src/core/src/Validation/Rule.php
Labels: feature

#55 improve: prevent circular recording in telescope
  src/telescope/src/Telescope.php
Labels: enhancement

#54 fix: fix customized provider class and ttl issues
  src/auth/src/Guards/JwtGuard.php
  src/jwt/src/JWTManager.php
Labels: bug

#53 fix: fix type hint in http kernel
  src/foundation/src/Http/Kernel.php
Labels: bug

#52 improve: better exception message in swoole table based cache
  src/cache/src/SwooleTable.php
Labels: enhancement

#58 fix: fix stream content in test response
  src/foundation/src/Testing/Http/TestResponse.php
Labels: bug

#59 chore: adjust stubs in devtool
  src/devtool/src/Generator/stubs/console.stub
  src/devtool/src/Generator/stubs/rule.stub
Labels: enhancement

#60 fix: remove route route dependencies cache
  src/http/src/RouteDependency.php
Labels: bug

#61 fix: fix view path config in service provider
  src/support/src/ServiceProvider.php
Labels: bug

#62 improve: optimize fireAfterResolvingCallbacks
  src/http/src/RouteDependency.php
Labels: enhancement

#63 chore: split class loader for extending features in the future
  src/foundation/src/ClassLoader.php
  tests/Foundation/Testing/ApplicationTestCase.php
Labels: others

#64 refactor: refactor dotenv loading with LoadEnvironmentVariables bootstrapper
  src/foundation/src/Application.php
  src/foundation/src/Bootstrap/LoadEnvironmentVariables.php
  src/foundation/src/ClassLoader.php
  src/foundation/src/Console/Kernel.php
  src/foundation/src/Contracts/Application.php
  src/foundation/src/Listeners/ReloadDotenvAndConfig.php
  tests/Foundation/Bootstrap/LoadEnvironmentVariablesTest.php
  tests/Foundation/fixtures/hyperf/.env
Labels: enhancement

#66 feat: add WithoutOverlapping middleware for queue
  src/queue/src/Middleware/WithoutOverlapping.php
Labels: feature

#68 fix: import missing EntriesRepository in IncomingEntry.php
  src/telescope/src/IncomingEntry.php
Labels: bug

#69 fix: correct the view path when load views in service provider
  src/support/src/ServiceProvider.php
Labels: bug

#70 feat: add channel class for coroutine
  src/coroutine/src/Channel.php
Labels: enhancement

#71 feat: implement process package
  composer.json
  phpstan.neon.dist
  phpunit.xml.dist
  src/process/LICENSE.md
  src/process/README.md
  src/process/composer.json
  src/process/src/Contracts/InvokedProcess.php
  src/process/src/Contracts/ProcessResult.php
  src/process/src/Exceptions/ProcessFailedException.php
  src/process/src/Exceptions/ProcessTimedOutException.php
  src/process/src/Factory.php
  src/process/src/FakeInvokedProcess.php
  src/process/src/FakeProcessDescription.php
  src/process/src/FakeProcessResult.php
  src/process/src/FakeProcessSequence.php
  src/process/src/InvokedProcess.php
  src/process/src/InvokedProcessPool.php
  src/process/src/PendingProcess.php
  src/process/src/Pipe.php
  src/process/src/Pool.php
  src/process/src/ProcessPoolResults.php
  src/process/src/ProcessResult.php
  src/support/src/Facades/Process.php
  src/support/src/Str.php
  tests/Process/ProcessTest.php
Labels: feature

#73 fix: fix autoload in composer.json
  phpunit.xml.dist
  src/process/composer.json
  tests/Process/ProcessTest.php
Labels: bug

#74 improve: run ProcessTest in test suite
  phpunit.xml.dist
  tests/Process/ProcessTest.php
Labels: enhancement

#75 feat: implement scheduling package
  composer.json
  src/foundation/composer.json
  src/foundation/src/Application.php
  src/foundation/src/Bootstrap/LoadScheduling.php
  src/foundation/src/ConfigProvider.php
  src/foundation/src/Console/CommandReplacer.php
  src/foundation/src/Console/Contracts/Kernel.php
  src/foundation/src/Console/Contracts/Schedule.php
  src/foundation/src/Console/Kernel.php
  src/foundation/src/Console/Scheduling/Schedule.php
  src/foundation/src/Contracts/Application.php
  src/scheduling/LICENSE.md
  src/scheduling/README.md
  src/scheduling/composer.json
  src/scheduling/src/CacheEventMutex.php
  src/scheduling/src/CacheSchedulingMutex.php
  src/scheduling/src/CallbackEvent.php
  src/scheduling/src/ConfigProvider.php
  src/scheduling/src/Console/ScheduleClearCacheCommand.php
  src/scheduling/src/Console/ScheduleInterruptCommand.php
  src/scheduling/src/Console/ScheduleListCommand.php
  src/scheduling/src/Console/ScheduleRunCommand.php
  src/scheduling/src/Console/ScheduleTestCommand.php
  src/scheduling/src/Contracts/CacheAware.php
  src/scheduling/src/Contracts/EventMutex.php
  src/scheduling/src/Contracts/SchedulingMutex.php
  src/scheduling/src/Event.php
  src/scheduling/src/Events/ScheduledTaskFailed.php
  src/scheduling/src/Events/ScheduledTaskFinished.php
  src/scheduling/src/Events/ScheduledTaskSkipped.php
  src/scheduling/src/Events/ScheduledTaskStarting.php
  src/scheduling/src/ManagesAttributes.php
  src/scheduling/src/ManagesFrequencies.php
  src/scheduling/src/PendingEventAttributes.php
  src/scheduling/src/Schedule.php
  src/support/src/DateFactory.php
  src/support/src/Facades/Artisan.php
  src/support/src/Facades/Date.php
  src/support/src/Facades/Schedule.php
  src/support/src/Functions.php
  src/support/src/helpers.php
  src/telescope/src/Watchers/ScheduleWatcher.php
  tests/Foundation/Bootstrap/LoadSchedulingTest.php
  tests/Process/ProcessTest.php
  tests/Scheduling/CacheEventMutexTest.php
  tests/Scheduling/CacheSchedulingMutexTest.php
  tests/Scheduling/EventTest.php
  tests/Scheduling/FrequencyTest.php
  tests/Scheduling/ScheduleTest.php
  tests/Telescope/Watchers/ScheduleWatcherTest.php
Labels: feature

#76 fix: remove unused command registering
  src/foundation/src/ConfigProvider.php
  tests/Foundation/Testing/BootstrapConfigProvider.php
Labels: bug

#77 feat: support system command in exec in schedule
  src/scheduling/src/Event.php
  src/scheduling/src/Schedule.php
  tests/Scheduling/EventTest.php
Labels: enhancement

#78 fix: make sure env is loaded in class loader
  src/foundation/src/Bootstrap/LoadEnvironmentVariables.php
  src/foundation/src/ClassLoader.php
  src/foundation/src/Console/Kernel.php
  tests/Foundation/Bootstrap/LoadEnvironmentVariablesTest.php
Labels: bug

#79 improve: add type hint for load function in console kernel
  src/foundation/src/Console/Contracts/Kernel.php
  src/foundation/src/Console/Kernel.php
Labels: enhancement

#80 feat: add schedule:stop command and support concurrency number in scheduling
  src/scheduling/src/ConfigProvider.php
  src/scheduling/src/Console/ScheduleRunCommand.php
  src/scheduling/src/Console/ScheduleStopCommand.php
Labels: enhancement

#81 feat: support requestVia in auth manager
  src/auth/src/AuthManager.php
  src/auth/src/Guards/GuardHelpers.php
  src/auth/src/Guards/JwtGuard.php
  src/auth/src/Guards/RequestGuard.php
  src/auth/src/Guards/SessionGuard.php
  tests/Auth/AuthMangerTest.php
Labels: feature

#82 feat: add make:policy command
  src/devtool/src/ConfigProvider.php
  src/devtool/src/Generator/PolicyCommand.php
  src/devtool/src/Generator/stubs/policy.plain.stub
  src/devtool/src/Generator/stubs/policy.stub
Labels: feature

#83 feat: add connection method in redis
  src/core/src/Redis/Redis.php
  src/support/src/Facades/Redis.php
Labels: feature

#84 feat: add cache for resolvedDependencies in route dependency
  src/http/src/RouteDependency.php
Labels: enhancement

#86 feat: add assertion functions for session
  src/foundation/src/Testing/Concerns/InteractsWithSession.php
  src/foundation/src/Testing/Concerns/MakesHttpRequests.php
  src/foundation/src/Testing/Http/TestResponse.php
  src/foundation/src/Testing/TestCase.php
  tests/Foundation/Testing/Concerns/MakesHttpRequestsTest.php
  tests/Foundation/Testing/TestResponseAssert.php
  tests/Foundation/fixtures/hyperf/routes/test-api.php
Labels: enhancement

#87 feat: add headers function in request
  src/http/src/Contracts/RequestContract.php
  src/http/src/Request.php
Labels: enhancement

#88 fix: fix namespace of TestResponseAssert
  src/foundation/src/Testing/Http/TestResponse.php
  src/foundation/src/Testing/TestResponseAssert.php
Labels: bug

#89 chore: add some type hints and return type declairation to testing traits
  src/foundation/src/Testing/Concerns/InteractsWithDatabase.php
  src/foundation/src/Testing/Traits/CanConfigureMigrationCommands.php
  src/support/src/Facades/DB.php
Labels: enhancement
