Repository laravel-hyperf/components, pull requests merged in 2025-02, with the labels that each got.

#2 fix: fix suggest package name in filesystem
  src/filesystem/composer.json
Labels: enhancement

#1 fix broadcasting error
  src/broadcasting/src/BroadcastManager.php
  src/broadcasting/src/Broadcasters/Broadcaster.php
  src/broadcasting/src/UniqueBroadcastEvent.php
Labels: bug

#3 feat: implement eloquent model observer
  src/core/src/Database/Eloquent/Concerns/HasObservers.php
  src/core/src/Database/Eloquent/Model.php
  src/core/src/Database/Eloquent/ObserverManager.php
  src/devtool/src/ConfigProvider.php
  src/devtool/src/Generator/ObserverCommand.php
  src/devtool/src/Generator/stubs/observer.stub
  src/foundation/src/Console/CommandReplacer.php
  tests/Core/ObserverManagerTest.php
Labels: feature

#5 feat: add hot-reload watcher command
  src/devtool/src/Commands/WatchCommand.php
  src/devtool/src/ConfigProvider.php
  src/foundation/src/Console/CommandReplacer.php
Labels: feature

#9 feat: add request response context
  src/core/src/Context/RequestContext.php
  src/core/src/Context/ResponseContext.php
Labels: feature

#8 feat: enrich blade compiler
  src/core/src/ConfigProvider.php
  src/core/src/View/CompilerFactory.php
  src/core/src/View/Compilers/BladeCompiler.php
  src/core/src/View/Compilers/Concerns/CompilesAuthorization.php
  src/core/src/View/Compilers/Concerns/CompilesHelpers.php
  src/core/src/View/Compilers/Concerns/CompilesInjections.php
  src/core/src/View/Compilers/Concerns/CompilesJs.php
  src/core/src/View/Compilers/Concerns/CompilesSession.php
  src/core/src/View/Compilers/Concerns/CompilesUseStatements.php
  src/foundation/src/helpers.php
  src/session/src/Functions.php
Labels: feature

#10 feat: support `without_middleware` in route collector
  src/router/src/RouteCollector.php
  tests/Router/RouteCollectorTest.php
Labels: feature

#11 feat: support file method in response
  src/http/src/Contracts/ResponseContract.php
  src/http/src/Response.php
  src/support/src/Facades/Response.php
  tests/Http/ResponseTest.php
Labels: feature

#12 feat: add arr, str and collection classes to support
  src/support/src/Arr.php
  src/support/src/Collection.php
  src/support/src/Str.php
Labels: feature

#13 feat: add some signature related methods to request
  src/http/src/Contracts/RequestContract.php
  src/http/src/Request.php
  src/support/src/Facades/Request.php
  src/support/src/Facades/URL.php
  tests/Http/RequestTest.php
Labels: feature

#14 feat: add ValidateSignature middleware
  src/router/composer.json
  src/router/src/Exceptions/InvalidSignatureException.php
  src/router/src/Middleware/ValidateSignature.php
Labels: feature

#15 chore: rename providers key of extra in composer.json
  composer.json
  src/config/src/ProviderConfig.php
  src/foundation/composer.json
  src/foundation/src/Bootstrap/RegisterProviders.php
  src/notifications/composer.json
  src/telescope/composer.json
  tests/Foundation/fixtures/hyperf1/composer.lock
Labels: others

#16 feat: extend support fluent class
  src/support/src/Fluent.php
Labels: feature

#17 feat: add DefaultProviders in ServiceProvider
  src/support/src/DefaultProviders.php
  src/support/src/ServiceProvider.php
Labels: feature

#18 feat: support broadcast channel in notification
  src/notifications/src/ChannelManager.php
  src/notifications/src/Channels/BroadcastChannel.php
  src/notifications/src/Events/BroadcastNotificationCreated.php
  src/notifications/src/Messages/BroadcastMessage.php
  tests/Notifications/NotificationBroadcastChannelTest.php
Labels: feature

#20 refactor: refactor model observer
  src/core/src/Database/Eloquent/Concerns/HasCallbacks.php
  src/core/src/Database/Eloquent/Model.php
  src/core/src/Database/Eloquent/ModelListener.php
  src/core/src/Database/Eloquent/ObserverManager.php
  tests/Core/ModelListenerTest.php
  tests/Core/ObserverManagerTest.php
Labels: enhancement

#21 feat: support BroadcastsEvents in model
  src/core/src/Database/Eloquent/BroadcastableModelEventOccurred.php
  src/core/src/Database/Eloquent/BroadcastsEvents.php
  src/core/src/Database/Eloquent/Model.php
Labels: feature

#22 feat: add HigherOrderTapProxy
  src/support/src/HigherOrderTapProxy.php
  src/support/src/helpers.php
  tests/HttpClient/HttpClientTest.php
Labels: feature

#19 fix phpdoc type declarations
  src/foundation/src/helpers.php
  src/support/src/Facades/DB.php
Labels: enhancement

#23 feat: add EloquentBroadcastingTest
  src/core/src/Database/Eloquent/BroadcastsEvents.php
  src/foundation/src/Testing/RefreshDatabase.php
  tests/Core/EloquentBroadcastingTest.php
  tests/Foundation/Testing/BootstrapConfigProvider.php
Labels: enhancement

#28 feat: extend collection in eloquent model
  src/core/src/Database/Eloquent/Collection.php
  src/core/src/Database/Eloquent/Model.php
  src/foundation/src/Application.php
Labels: others

#29 feat: implement UrlGenerator contract
  src/foundation/src/Application.php
  src/foundation/src/Exceptions/Handler.php
  src/foundation/src/helpers.php
  src/http/src/Request.php
  src/router/src/ConfigProvider.php
  src/router/src/Contracts/UrlGenerator.php
  src/router/src/Functions.php
  src/router/src/UrlGenerator.php
  src/support/src/Facades/URL.php
  tests/Foundation/FoundationExceptionHandlerTest.php
  tests/Http/RequestTest.php
  tests/Router/FunctionsTest.php
Labels: enhancement

#31 chore: use support's extended collection and fluent
  src/broadcasting/composer.json
  src/broadcasting/src/Broadcasters/Broadcaster.php
  src/http-client/composer.json
  src/http-client/src/Factory.php
  src/http-client/src/PendingRequest.php
  src/http-client/src/Request.php
  src/http-client/src/Response.php
  src/http/src/Contracts/RequestContract.php
  src/http/src/Request.php
  src/http/src/Response.php
  tests/HttpClient/HttpClientTest.php
Labels: others

#32 feat: support setting config provider in laravel-hyperf's extra in composer.json
  src/config/src/ProviderConfig.php
Labels: feature

#33 feat: add isLacale method in application
  src/foundation/src/Application.php
  src/foundation/src/Contracts/Application.php
  src/support/src/Facades/Lang.php
Labels: feature

#34 fix: fix migration filename of telescope package
  src/telescope/database/migrations/2025_02_08_000000_create_telescope_entries_table.php
Labels: bug

#30 update facade documents
  src/broadcasting/src/BroadcastManager.php
  src/cache/src/CacheManager.php
  src/http-client/src/Factory.php
  src/mail/src/MailManager.php
  src/router/src/Router.php
  src/support/src/Facades/App.php
  src/support/src/Facades/Artisan.php
  src/support/src/Facades/Auth.php
  src/support/src/Facades/Blade.php
  src/support/src/Facades/Broadcast.php
  src/support/src/Facades/Bus.php
  src/support/src/Facades/Cache.php
  src/support/src/Facades/Config.php
  src/support/src/Facades/Cookie.php
  src/support/src/Facades/Crypt.php
  src/support/src/Facades/DB.php
  src/support/src/Facades/Date.php
  src/support/src/Facades/Environment.php
  src/support/src/Facades/Event.php
  src/support/src/Facades/File.php
  src/support/src/Facades/Gate.php
  src/support/src/Facades/Hash.php
  src/support/src/Facades/Http.php
  src/support/src/Facades/JWT.php
  src/support/src/Facades/Lang.php
  src/support/src/Facades/Log.php
  src/support/src/Facades/Mail.php
  src/support/src/Facades/Notification.php
  src/support/src/Facades/Queue.php
  src/support/src/Facades/Redis.php
  src/support/src/Facades/Request.php
  src/support/src/Facades/Response.php
  src/support/src/Facades/Route.php
  src/support/src/Facades/Schedule.php
  src/support/src/Facades/Session.php
  src/support/src/Facades/Storage.php
  src/support/src/Facades/URL.php
  src/support/src/Facades/Validator.php
  src/support/src/Facades/View.php
Labels: enhancement

#36 feat: extend JsonResource and ResourceCollection
  composer.json
  src/http/composer.json
  src/http/src/Resources/Concerns/CollectsResources.php
  src/http/src/Resources/Json/AnonymousResourceCollection.php
  src/http/src/Resources/Json/JsonResource.php
  src/http/src/Resources/Json/ResourceCollection.php
  tests/Http/Resource/JsonResourceTest.php
  tests/Http/Resource/ResourceCollectionTest.php
Labels: feature

#38 feat: support collision as error renderer for console
  composer.json
  src/foundation/src/Console/ApplicationFactory.php
  src/foundation/src/Console/Command.php
  src/foundation/src/Console/ErrorRenderer.php
Labels: feature

#39 feat: support tag option in vendor:publish command
  src/foundation/src/Console/Commands/VendorPublishCommand.php
Labels: feature

#40 fix: fix count assertions in mockery and add carbon's mock
  src/foundation/src/Testing/TestCase.php
  tests/Foundation/Testing/Concerns/InteractsWithAuthenticationTest.php
  tests/Foundation/Testing/DatabaseMigrationsTest.php
  tests/Foundation/Testing/RefreshDatabaseTest.php
  tests/Telescope/Watchers/MailWatcherTest.php
Labels: bug

#41 feat: add Stringable and value to support
  src/support/src/Functions.php
  src/support/src/Stringalble.php
Labels: feature

#37 dont-discover should scan project's composer.json too
  src/config/src/ProviderConfig.php
  src/foundation/src/Bootstrap/RegisterProviders.php
  tests/Foundation/Bootstrap/RegisterProvidersTest.php
  tests/Foundation/fixtures/hyperf1/composer.json
  tests/Foundation/fixtures/hyperf1/composer.lock
Labels: feature

#42 feat: support setting class aliases in composer.json
  src/foundation/src/Bootstrap/RegisterFacades.php
  tests/Foundation/Bootstrap/RegisterFacadesTest.php
  tests/Foundation/fixtures/hyperf1/composer.json
Labels: feature
